import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../src/components/Navbar'

import 'bootstrap/dist/css/bootstrap.min.css'
import styles from '../styles/Home.module.css'
import Slider from '../src/components/Slider'
import Products from '../src/components/Products'
import Carta from '../src/components/Carta'
import { useState, useEffect } from 'react'

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    setShowModal(true);
  }, []);

  const handleShow = () => setShowModal(true);

  return (
    <>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar handleShow={handleShow} />
      <Slider/>
      <div className='product-area bg-image-1 pt-100 pb-95'>
        <div className='product-area-content'>
        <Products/>
        </div>
      </div>
      

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    <Carta showModal={showModal} setShowModal={setShowModal} />
    </>
  )
}
